### ISSUE TITLE
how to init schema?

### ISSUE THREAD

**Issue by glensc** [micgro42/dokuwiki-plugin-swarmwebhook#3]
1. installed the plugin
2. tried example syntax
3. failed

```
Schema swarm does not exist! [Search.php:75]

#0 /usr/share/dokuwiki/lib/plugins/struct/meta/SearchConfig.php(45): dokuwiki\plugin\struct\meta\Search->addSchema('swarm', '')
#1 /usr/share/dokuwiki/lib/plugins/struct/syntax/table.php(93): dokuwiki\plugin\struct\meta\SearchConfig->__construct(Array)
#2 /usr/share/dokuwiki/inc/parser/renderer.php(111): syntax_plugin_struct_table->render('xhtml', Object(Doku_Renderer_xhtml), Array)
#3 [internal function]: Doku_Renderer->plugin('struct_table', Array, 5, '---- struct tab...')
#4 /usr/share/dokuwiki/inc/parserutils.php(654): call_user_func_array(Array, Array)
#5 /usr/share/dokuwiki/inc/html.php(282): p_render('xhtml', Array, NULL)
#6 /usr/share/dokuwiki/inc/Action/Preview.php(25): html_show('====== struct =...')
#7 /usr/share/dokuwiki/inc/template.php(98): dokuwiki\Action\Preview->tplContent()
#8 /usr/share/dokuwiki/inc/events.php(111): tpl_content_core('preview')
#9 /usr/share/dokuwiki/inc/events.php(256): Doku_Event->trigger('tpl_content_cor...', true)
#10 /usr/share/dokuwiki/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'preview', 'tpl_content_cor...')
#11 /usr/share/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
#12 /usr/share/dokuwiki/inc/actions.php(27): include('/usr/share/doku...')
#13 /usr/share/dokuwiki/doku.php(120): act_dispatch()
#14 {main}
```

**Comment by micgro42** [comment]
There is a `swarm.struct.json` in the plugin directory. You can import this to initialize the schema. I'll add that info to dokuwiki.org :+1:

**Comment by glensc** [comment]
there's no support for automatically importing it? or via commandline?

for example sqlite plugin supports some schema migration
